version: '3.8'
services:
  ollama:
    image: dustynv/ollama:0.6.8-r36.4
    # ports:
      # - 11434:11434
    volumes:
      - ~/.ollama/models:/data/models/ollama/models
    container_name: ollama
    tty: true
    restart: unless-stopped
    # enviroment:
    #   - OLLAMA_FLASH_ATTENTION=1
    #   # - OLLAMA_KV_CACHE=q8_0
    #   - OLLAMA_CONTEXT_LENGTH=8192 
    networks:
      - ollama-proxy

  nginx:
    image: openresty/openresty:jammy
    container_name: nginx_ollama_proxy
    ports:
      - 11434:11434
    volumes:
      - ~/nginx/ollama_proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ~/nginx/logs:/var/log/nginx
    restart: always
    networks:
      - ollama-proxy
    depends_on:
      - ollama

networks:
  ollama-proxy: