FROM openresty/openresty:jammy
RUN /usr/local/openresty/luajit/bin/luarocks install lua-resty-http 

# docker build -t openresty/openresty:mine .
# docker tag openresty/openresty:mine localhost:5000/openresty/openresty:mine