services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - ./ollama_data:/root/.ollama
    restart: always
    environment:
      - OLLAMA_HOST="0.0.0.0"
      - OLLAMA_FLASH_ATTENTION=1
    networks:
      - ollama-proxy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # alternatively, use `count: all` for all GPUs
              capabilities: [gpu]

  nginx:
    image: openresty/openresty:jammy
    container_name: nginx_ollama_proxy
    ports:
      - 11434:11434
    volumes:
      - ~/nginx/ollama_proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ~/nginx/logs:/var/log/nginx
    restart: always
    networks:
      - ollama-proxy
    depends_on:
      - ollama

networks:
  ollama-proxy: